#!/usr/bin/env bash
#
# The hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# The hook encrypts the .env file if present in the repository

## Read the README if you get any error. DO NOT bypass the PRE-COMMIT HOOK

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail


__env_file=".env"

if [ ! -f ${__env_file} ]; then
    echo "Environment file not present, Nothing to do!"
	echo "Proceeding with normal commit"
	exit 0
fi

echo "Environment file present"
echo "Beginning Encryption Process"

git secret add ${__env_file}

git secret hide

git add ${__env_file}.secret

echo "Encryption of files successfull"
exit 0
